name: Обновление матрицы от Росминздрава (ежедневно)

on:
  schedule:
    - cron: "0 3 * * *" # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Предоставляет права на запись для пуша изменений
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: pip install pandas requests openpyxl

      - name: Скачивание и преобразование Excel в JSON
        run: |
          import pandas as pd
          import json
          import requests
          from io import BytesIO
          import datetime
          import os

          existing_url = "https://raw.githubusercontent.com/WIN4ig/IOM/refs/heads/main/data/matrix.json"
          try:
              existing_r = requests.get(existing_url)
              existing_r.raise_for_status()
              existing_data = existing_r.json()

              # Сохраняем пары (iom, specialty) для всех записей и отдельно для is_new=true
              existing_all_items = {(item["iom"], item["specialty"]) for item in existing_data["items"]}
              existing_new_items = {(item["iom"], item["specialty"]) for item in existing_data["items"] if item.get("is_new", False)}

          except:
              existing_all_items = set()
              existing_new_items = set()

          url = "https://static.edu.rosminzdrav.ru/portal/common/instructions/Matrix_IOM-CR-dolgnost-.xlsx"
          r = requests.get(url)
          r.raise_for_status()

          xls = pd.read_excel(BytesIO(r.content), sheet_name=0, header=1)
          xls.dropna(how="all", inplace=True)

          result = []
          columns = list(xls.columns)

          col_num = columns.index("Номер ИОМ-КР")
          col_iom = columns.index("Название ИОМ-КР/Должность")

          skip_cols = ("Применение", "Номер ИОМ-КР", "Название ИОМ-КР/Должность", "Дата начала предоставления доступа")

          for idx, row in xls.iterrows():
              iom_name = str(row[col_iom]).strip() if pd.notna(row[col_iom]) else ""
              iom_number = str(row[col_num]).strip() if pd.notna(row[col_num]) else ""
              for col in columns:
                  if col in skip_cols:
                      continue
                  if isinstance(col, str) and col.strip() != "" and pd.notna(row[col]):
                      clean_col = col.strip().lstrip("*")

                      key = (iom_name, clean_col)
                      # Установка is_new: если раньше была true - остается true
                      # если это новая пара (отсутствует в all_items) - true
                      # иначе false
                      is_new = key in existing_new_items or key not in existing_all_items

                      result.append({
                          "specialty": clean_col,
                          "iom": iom_name,
                          "iom_number": iom_number,
                          "is_new": is_new
                      })

          specialties = sorted(set(item["specialty"] for item in result if item["specialty"]))

          data = {
              "items": result,
              "specialties": specialties,
              "updated_at": datetime.datetime.now(datetime.timezone.utc).isoformat()
          }

          os.makedirs("data", exist_ok=True)
          with open("data/matrix.json", "w", encoding="utf-8") as f:
              json.dump(data, f, ensure_ascii=False, indent=2)

          print(f"Сохранено {len(result)} записей в data/matrix.json")
        shell: python

      - name: Коммит и пуш изменений в main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/matrix.json
          if git diff --cached --quiet; then
            echo "Нет изменений в matrix.json"
          else
            git commit -m "Обновление matrix.json"
            git push
          fi

      - name: Синхронизация с gh-pages (для GitHub Pages)
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git merge main --no-edit --allow-unrelated-histories || true
            git add -A
            git commit -m "Синхронизация matrix.json с main" || echo "Нет изменений для коммита"
            git push origin gh-pages
          else
            echo "Ветка gh-pages не найдена. Создайте её в репозитории и настройте GitHub Pages."
          fi