name: Обновление матрицы от Росминздрава (ежедневно)

on:
  schedule:
    - cron: "0 3 * * *" # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Предоставляет права на запись для пуша изменений
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Используем GITHUB_TOKEN для аутентификации

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: pip install pandas requests openpyxl

      - name: Скачивание и преобразование Excel в JSON
        run: |
          import pandas as pd
          import json
          import requests
          from io import BytesIO

          url = "https://static.edu.rosminzdrav.ru/portal/common/instructions/Matrix_IOM-CR-dolgnost-.xlsx"
          r = requests.get(url)
          r.raise_for_status()

          # Читаем Excel, вторая строка — заголовки
          xls = pd.read_excel(BytesIO(r.content), sheet_name=0, header=1)
          xls.dropna(how="all", inplace=True)

          result = []
          columns = list(xls.columns)

          # Индексы основных колонок
          col_num = columns.index("Номер ИОМ-КР")
          col_iom = columns.index("Название ИОМ-КР/Должность")

          for idx, row in xls.iterrows():
              iom_name = str(row[col_iom]).strip() if pd.notna(row[col_iom]) else ""
              for col in columns:
                  if col in ("Номер ИОМ-КР", "Название ИОМ-КР/Должность", "Дата начала предоставления доступа"):
                      continue
                  if isinstance(col, str) and col.strip() != "" and pd.notna(row[col]):
                      result.append({
                          "specialty": col.strip().lstrip("*"),
                          "iom": iom_name,
                          "position": col.strip().lstrip("*")
                      })

          # Сохраняем JSON
          import os
          os.makedirs("data", exist_ok=True)
          with open("data/matrix.json", "w", encoding="utf-8") as f:
              json.dump(result, f, ensure_ascii=False, indent=2)

          print(f"Сохранено {len(result)} записей в data/matrix.json")
        shell: python

      - name: Коммит и пуш изменений
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/matrix.json
          if git diff --cached --quiet; then
            echo "Нет изменений в matrix.json"
          else
            git commit -m "Обновление matrix.json"
            git push
          fi